const MENU_LIST = [
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    materia: "Electronica",
    boleta: "2018301731",
    profesor: "Rafael Trujillo",
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
];

module.exports = {
  content: [
    {
      image: "./imagenes/upiita.png",
      fit: [80, 80],
      style: "imagenes",
      image: "./imagenes/ipn.png",
      fit: [80, 80],
    },

    {
      text: "Documento de adeudo \n ",
      style: "header",
    },

    {
      text: "El sistema de gestion de laboratorios avala que el alumno \n ",
      style: "label",
    },
    {
      text: ` ${MENU_LIST[0].nombrealumno}  \n `,
      style: "label",
    },

    {
      text: `Con numero de boleta ${MENU_LIST[0].boleta}, el cual se encuentra inscrito en la carrera de ${MENU_LIST[0].Carrera} 
       Adeuda materiales en los siguientes laboratorios laboratorios de: \n 
        ${MENU_LIST[0].nombrelaboratorio} Teniendo un adeudo de ${MENU_LIST[0].nombreequipo} \n
        ${MENU_LIST[1].nombrelaboratorio} Teniendo un adeudo de ${MENU_LIST[1].nombreequipo} \n 
        ${MENU_LIST[2].nombrelaboratorio} Teniendo un adeudo de ${MENU_LIST[2].nombreequipo} \n 
        ${MENU_LIST[3].nombrelaboratorio}  Teniendo un adeudo de ${MENU_LIST[3].nombreequipo}\n 
        ${MENU_LIST[4].nombrelaboratorio}  Teniendo un adeudo de ${MENU_LIST[4].nombreequipo}\n 
        ${MENU_LIST[5].nombrelaboratorio}  Teniendo un adeudo de ${MENU_LIST[5].nombreequipo}\n 
        ${MENU_LIST[6].nombrelaboratorio} Teniendo un adeudo de ${MENU_LIST[6].nombreequipo} \n
        ${MENU_LIST[7].nombrelaboratorio} Teniendo un adeudo de ${MENU_LIST[7].nombreequipo} \n 
        ${MENU_LIST[8].nombrelaboratorio} Teniendo un adeudo de ${MENU_LIST[8].nombreequipo} \n 
        ${MENU_LIST[9].nombrelaboratorio}  Teniendo un adeudo de ${MENU_LIST[9].nombreequipo}\n 
        ${MENU_LIST[10].nombrelaboratorio}  Teniendo un adeudo de ${MENU_LIST[10].nombreequipo}\n 
        ${MENU_LIST[11].nombrelaboratorio}  Teniendo un adeudo de ${MENU_LIST[11].nombreequipo}\n  `,
      style: "label",
    },
  ],
};
