const MENU_LIST = [
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Angel",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: false,
    fecha_entrega: "2022-01-01T00:00:00.000Z",
    fecha_peticion: "2022-06-02T00:00:00.000Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
  {
    idlaboratorio: "9",
    nombrelaboratorio: "Física 1",
    nombrealumno: "Miguel Salomon",
    carrera: "Telematica",
    correo: "mikael.angelo.txt@gmail.com",
    estatus: true,
    fecha_entrega: "2022-10-14T17:19:58.430Z",
    fecha_peticion: "2022-10-14T17:19:58.430Z",
    idequipo: 88,
    nombreequipo: "Resistencia 330 Ohm",
    codigo_barras: null,
    modelo: null,
    ano: null,
    Foto_fallo: null,
  },
];

module.exports = {
  content: [
    {
      image: "./imagenes/upiita.png",
      fit: [80, 80],
      style: "imagenes",
      image: "./imagenes/ipn.png",
      fit: [80, 80],
    },

    {
      text: "Documento de adeudo \n ",
      style: "header",
    },

    {
      text: "El sistema de gestion de laboratorios avala que el alumno \n ",
      style: "label",
    },
    {
      text: ` ${MENU_LIST.nombrealumno}  \n `,
      style: "label",
    },

    {
      text: `Con numero de boleta ${MENU_LIST.boleta}, el cual se encuentra inscrito en la carrera de ${MENU_LIST.Carrera} 
        no adeuda ningun material ni equipo dentro de los laboratorios de: \n 
        Fisica 1 \n 
        Fisica 2 \n 
        Electronica 1 \n
        Electronica 2 \n 
        Electronica 3 \n 
        Sistemas Digitales 1 \n 
        Sistemas Digitales 2 \n 
        Quimica y Biologia \n 
        Metrologia \n 
        Maquinas y Herramientas \n  
      `,
      style: "label",
    },
  ],
};
